spring:
  application:
    name: webhook-sms-api

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  port: 8239
  servlet:
    context-path: /webhook-sms

logging:
  level:
    com.familia: DEBUG

twilio:
  account-sid: TU_ACCOUNT_SID_AQUI
  auth-token: TU_AUTH_TOKEN_AQUI
  from-number: "+TU_NUMERO_AQUI"

webhook:
  secret: TU_SECRETO_AQUI
